# Generated by Django 3.1.4 on 2021-02-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quizmodel',
        ),
        migrations.DeleteModel(
            name='quizmodel1',
        ),
        migrations.AddField(
            model_name='quizmodel2',
            name='Verification',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
