# Generated by Django 3.1.4 on 2021-02-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210214_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel2',
            name='quiz_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
